// Code generated by protoc-gen-go. DO NOT EDIT.
// source: format.proto

package otsimo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Validator struct {
	MinLength            *int32   `protobuf:"varint,1,opt,name=minLength" json:"minLength,omitempty"`
	Regex                *string  `protobuf:"bytes,2,opt,name=regex" json:"regex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Validator) Reset()         { *m = Validator{} }
func (m *Validator) String() string { return proto.CompactTextString(m) }
func (*Validator) ProtoMessage()    {}
func (*Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d9ed1f28583505e, []int{0}
}

func (m *Validator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Validator.Unmarshal(m, b)
}
func (m *Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Validator.Marshal(b, m, deterministic)
}
func (m *Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validator.Merge(m, src)
}
func (m *Validator) XXX_Size() int {
	return xxx_messageInfo_Validator.Size(m)
}
func (m *Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_Validator proto.InternalMessageInfo

func (m *Validator) GetMinLength() int32 {
	if m != nil && m.MinLength != nil {
		return *m.MinLength
	}
	return 0
}

func (m *Validator) GetRegex() string {
	if m != nil && m.Regex != nil {
		return *m.Regex
	}
	return ""
}

var E_Format = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         64003,
	Name:          "otsimo_form.format",
	Tag:           "bytes,64003,opt,name=format",
	Filename:      "format.proto",
}

var E_Readonly = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         64004,
	Name:          "otsimo_form.readonly",
	Tag:           "varint,64004,opt,name=readonly",
	Filename:      "format.proto",
}

var E_HasDynamicSource = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.FieldOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         61005,
	Name:          "otsimo_form.hasDynamicSource",
	Tag:           "varint,61005,opt,name=hasDynamicSource",
	Filename:      "format.proto",
}

var E_SourceKey = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         64005,
	Name:          "otsimo_form.sourceKey",
	Tag:           "bytes,64005,opt,name=sourceKey",
	Filename:      "format.proto",
}

var E_Validator = &proto.ExtensionDesc{
	ExtendedType:  (*descriptorpb.FieldOptions)(nil),
	ExtensionType: (*Validator)(nil),
	Field:         64007,
	Name:          "otsimo_form.validator",
	Tag:           "bytes,64007,opt,name=validator",
	Filename:      "format.proto",
}

func init() {
	proto.RegisterType((*Validator)(nil), "otsimo_form.Validator")
	proto.RegisterExtension(E_Format)
	proto.RegisterExtension(E_Readonly)
	proto.RegisterExtension(E_HasDynamicSource)
	proto.RegisterExtension(E_SourceKey)
	proto.RegisterExtension(E_Validator)
}

func init() { proto.RegisterFile("format.proto", fileDescriptor_9d9ed1f28583505e) }

var fileDescriptor_9d9ed1f28583505e = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0xcb, 0x2f, 0xca,
	0x4d, 0x2c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xce, 0x2f, 0x29, 0xce, 0xcc, 0xcd,
	0x8f, 0x07, 0x09, 0x4a, 0x29, 0xa4, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea, 0x83, 0xa5, 0x92, 0x4a,
	0xd3, 0xf4, 0x53, 0x52, 0x8b, 0x93, 0x8b, 0x32, 0x0b, 0x4a, 0xf2, 0x8b, 0x20, 0xca, 0x95, 0xec,
	0xb9, 0x38, 0xc3, 0x12, 0x73, 0x32, 0x53, 0x12, 0x4b, 0xf2, 0x8b, 0x84, 0x64, 0xb8, 0x38, 0x73,
	0x33, 0xf3, 0x7c, 0x52, 0xf3, 0xd2, 0x4b, 0x32, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0x10,
	0x02, 0x42, 0x22, 0x5c, 0xac, 0x45, 0xa9, 0xe9, 0xa9, 0x15, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x9c,
	0x41, 0x10, 0x8e, 0x95, 0x39, 0x17, 0x1b, 0xc4, 0x7e, 0x21, 0x59, 0x3d, 0x88, 0x6d, 0x7a, 0x30,
	0xdb, 0xf4, 0xdc, 0x32, 0x53, 0x73, 0x52, 0xfc, 0x0b, 0x4a, 0x32, 0xf3, 0xf3, 0x8a, 0x25, 0x9a,
	0xbf, 0x30, 0x83, 0xf5, 0x41, 0x95, 0x5b, 0x59, 0x73, 0x71, 0x14, 0xa5, 0x26, 0xa6, 0xe4, 0xe7,
	0xe5, 0x54, 0x12, 0xd2, 0xda, 0x02, 0xd6, 0xca, 0x11, 0x04, 0xd7, 0x60, 0xe5, 0xcd, 0x25, 0x90,
	0x91, 0x58, 0xec, 0x52, 0x99, 0x97, 0x98, 0x9b, 0x99, 0x1c, 0x9c, 0x5f, 0x5a, 0x94, 0x9c, 0x4a,
	0xc8, 0x90, 0xb3, 0x77, 0x20, 0x86, 0x60, 0x68, 0xb4, 0xb2, 0xe5, 0xe2, 0x2c, 0x06, 0xb3, 0xbc,
	0x53, 0x09, 0x3a, 0xa5, 0x15, 0xea, 0x0b, 0x84, 0x0e, 0xab, 0x50, 0x2e, 0xce, 0x32, 0x78, 0x10,
	0x12, 0xd0, 0xde, 0x0e, 0xd6, 0xce, 0x6d, 0x24, 0xa6, 0x87, 0x14, 0x4d, 0x7a, 0xf0, 0x18, 0x08,
	0x42, 0x98, 0x04, 0x08, 0x00, 0x00, 0xff, 0xff, 0x14, 0x10, 0x43, 0x35, 0xd7, 0x01, 0x00, 0x00,
}
