// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pagination.proto

package otsimo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PaginationQuery_Sort int32

const (
	PaginationQuery_ASC  PaginationQuery_Sort = 0
	PaginationQuery_DESC PaginationQuery_Sort = 1
)

var PaginationQuery_Sort_name = map[int32]string{
	0: "ASC",
	1: "DESC",
}

var PaginationQuery_Sort_value = map[string]int32{
	"ASC":  0,
	"DESC": 1,
}

func (x PaginationQuery_Sort) String() string {
	return proto.EnumName(PaginationQuery_Sort_name, int32(x))
}

func (PaginationQuery_Sort) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_567bfb3a87c868dd, []int{0, 0}
}

type PaginationQuery struct {
	FieldValue           string               `protobuf:"bytes,1,opt,name=field_value,json=fieldValue,proto3" json:"field_value,omitempty"`
	FieldName            string               `protobuf:"bytes,2,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	Sort                 PaginationQuery_Sort `protobuf:"varint,3,opt,name=sort,proto3,enum=otsimo.PaginationQuery_Sort" json:"sort,omitempty"`
	Limit                int32                `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *PaginationQuery) Reset()         { *m = PaginationQuery{} }
func (m *PaginationQuery) String() string { return proto.CompactTextString(m) }
func (*PaginationQuery) ProtoMessage()    {}
func (*PaginationQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_567bfb3a87c868dd, []int{0}
}

func (m *PaginationQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaginationQuery.Unmarshal(m, b)
}
func (m *PaginationQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaginationQuery.Marshal(b, m, deterministic)
}
func (m *PaginationQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaginationQuery.Merge(m, src)
}
func (m *PaginationQuery) XXX_Size() int {
	return xxx_messageInfo_PaginationQuery.Size(m)
}
func (m *PaginationQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_PaginationQuery.DiscardUnknown(m)
}

var xxx_messageInfo_PaginationQuery proto.InternalMessageInfo

func (m *PaginationQuery) GetFieldValue() string {
	if m != nil {
		return m.FieldValue
	}
	return ""
}

func (m *PaginationQuery) GetFieldName() string {
	if m != nil {
		return m.FieldName
	}
	return ""
}

func (m *PaginationQuery) GetSort() PaginationQuery_Sort {
	if m != nil {
		return m.Sort
	}
	return PaginationQuery_ASC
}

func (m *PaginationQuery) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type Pagination struct {
	// Types that are valid to be assigned to Pagination:
	//	*Pagination_Token
	//	*Pagination_Query
	Pagination           isPagination_Pagination `protobuf_oneof:"pagination"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_567bfb3a87c868dd, []int{1}
}

func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (m *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(m, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

type isPagination_Pagination interface {
	isPagination_Pagination()
}

type Pagination_Token struct {
	Token string `protobuf:"bytes,1,opt,name=token,proto3,oneof"`
}

type Pagination_Query struct {
	Query *PaginationQuery `protobuf:"bytes,2,opt,name=query,proto3,oneof"`
}

func (*Pagination_Token) isPagination_Pagination() {}

func (*Pagination_Query) isPagination_Pagination() {}

func (m *Pagination) GetPagination() isPagination_Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *Pagination) GetToken() string {
	if x, ok := m.GetPagination().(*Pagination_Token); ok {
		return x.Token
	}
	return ""
}

func (m *Pagination) GetQuery() *PaginationQuery {
	if x, ok := m.GetPagination().(*Pagination_Query); ok {
		return x.Query
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Pagination) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Pagination_OneofMarshaler, _Pagination_OneofUnmarshaler, _Pagination_OneofSizer, []interface{}{
		(*Pagination_Token)(nil),
		(*Pagination_Query)(nil),
	}
}

func _Pagination_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Pagination)
	// pagination
	switch x := m.Pagination.(type) {
	case *Pagination_Token:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Token)
	case *Pagination_Query:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Query); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Pagination.Pagination has unexpected type %T", x)
	}
	return nil
}

func _Pagination_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Pagination)
	switch tag {
	case 1: // pagination.token
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Pagination = &Pagination_Token{x}
		return true, err
	case 2: // pagination.query
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PaginationQuery)
		err := b.DecodeMessage(msg)
		m.Pagination = &Pagination_Query{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Pagination_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Pagination)
	// pagination
	switch x := m.Pagination.(type) {
	case *Pagination_Token:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Token)))
		n += len(x.Token)
	case *Pagination_Query:
		s := proto.Size(x.Query)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterEnum("otsimo.PaginationQuery_Sort", PaginationQuery_Sort_name, PaginationQuery_Sort_value)
	proto.RegisterType((*PaginationQuery)(nil), "otsimo.PaginationQuery")
	proto.RegisterType((*Pagination)(nil), "otsimo.Pagination")
}

func init() { proto.RegisterFile("pagination.proto", fileDescriptor_567bfb3a87c868dd) }

var fileDescriptor_567bfb3a87c868dd = []byte{
	// 242 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x50, 0x4d, 0x4b, 0xc3, 0x40,
	0x14, 0xec, 0xda, 0xa4, 0xb6, 0x53, 0xd1, 0xf0, 0x10, 0x8d, 0xa0, 0x18, 0x72, 0xca, 0x29, 0x4a,
	0xfd, 0x05, 0xb6, 0x0a, 0x9e, 0x44, 0x13, 0xf0, 0xe0, 0xa5, 0xac, 0xba, 0xca, 0x62, 0x92, 0x57,
	0xb7, 0x5b, 0xc1, 0xff, 0xe5, 0x0f, 0x94, 0xdd, 0x15, 0x0b, 0x42, 0x8f, 0xf3, 0xf1, 0xde, 0x0c,
	0x83, 0x64, 0x21, 0xdf, 0x74, 0x27, 0xad, 0xe6, 0xae, 0x5c, 0x18, 0xb6, 0x4c, 0x03, 0xb6, 0x4b,
	0xdd, 0x72, 0xfe, 0x2d, 0xb0, 0x77, 0xf7, 0x27, 0xde, 0xaf, 0x94, 0xf9, 0xa2, 0x53, 0x8c, 0x5f,
	0xb5, 0x6a, 0x5e, 0xe6, 0x9f, 0xb2, 0x59, 0xa9, 0x54, 0x64, 0xa2, 0x18, 0x55, 0xf0, 0xd4, 0x83,
	0x63, 0xe8, 0x04, 0x01, 0xcd, 0x3b, 0xd9, 0xaa, 0x74, 0xcb, 0xeb, 0x23, 0xcf, 0xdc, 0xca, 0x56,
	0xd1, 0x39, 0xa2, 0x25, 0x1b, 0x9b, 0xf6, 0x33, 0x51, 0xec, 0x4e, 0x8e, 0xcb, 0x10, 0x55, 0xfe,
	0x8b, 0x29, 0x6b, 0x36, 0xb6, 0xf2, 0x4e, 0xda, 0x47, 0xdc, 0xe8, 0x56, 0xdb, 0x34, 0xca, 0x44,
	0x11, 0x57, 0x01, 0xe4, 0x47, 0x88, 0x9c, 0x87, 0xb6, 0xd1, 0xbf, 0xac, 0x67, 0x49, 0x8f, 0x86,
	0x88, 0xae, 0xae, 0xeb, 0x59, 0x22, 0xf2, 0x67, 0x60, 0xfd, 0x8e, 0x0e, 0x10, 0x5b, 0x7e, 0x57,
	0x5d, 0xa8, 0x7a, 0xd3, 0xab, 0x02, 0xa4, 0x33, 0xc4, 0x1f, 0x2e, 0xca, 0x57, 0x1c, 0x4f, 0x0e,
	0x37, 0x34, 0x71, 0x07, 0xde, 0x37, 0xdd, 0x01, 0xd6, 0x4b, 0x4d, 0x87, 0x8f, 0xbf, 0x2b, 0x3d,
	0x0d, 0xfc, 0x68, 0x17, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf1, 0xb6, 0xa3, 0xc9, 0x48, 0x01,
	0x00, 0x00,
}
